---
title: "MT County update"
date: "3/28/2020"
output: html_document
---

First load in the data.  Currently have to download the NyTimes county level data by hand and put it in the local directory. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
library(tidyverse)
library(lubridate)
library(reshape2)
library(ggplot2)
library(plotly)
#read in the JH data
jh.cases <- read_csv("https://coviddata.github.io/covid-api/v1/places/cases.csv")
# having trouble loading from the webpage. Currently need to download to the local directory
nyt.cases <- read_csv("us-counties.csv")
mt.cases <- nyt.cases %>% filter(state == "Montana") %>% 
  mutate(county = as.factor(county))
```

Plot of the cases by county in Montana, but skip the zeros for now.
```{r co-plot}
dat <- mt.cases %>% filter(cases > 0)

first.day <- min(dat$date)
last.day <- max(dat$date)
n.days = as.numeric(last.day - first.day + 1)
dat2 <- data.frame(date = seq(from = first.day, to = last.day, by = 1),
                   cases = 1 * (1+.33) ^ seq(1, n.days, 1))

p <- ggplot(dat, aes(x = date, y = cases, color = county)) + 
  geom_line() +
#  geom_line(dat2, aes(x = date, y = cases, color = "black"), linetype = "dotted", size = 1.5) + 
  labs(x = "Date", y = "Cases") + theme_bw() + theme(legend.position="none") 

ggplotly(p)

```

And on a log scale: 

```{r co-plot-log}
p.log <- ggplot(dat, aes(x = date, y = cases, color = county)) + 
  geom_line() +
  labs(x = "Date", y = "Cases") + theme_bw() + theme(legend.position="none") + 
  scale_y_continuous(trans = 'log2') 

ggplotly(p.log)

```
