---
title: "MT County update"
date: "3/28/2020"
output: html_document
---

First load in the data.  Currently have to download the NyTimes county level data by hand and put it in the local directory. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
library(tidyverse)
library(lubridate)
library(reshape2)
library(ggplot2)
library(plotly)
#read in the JH data
jh.cases <- read_csv("https://coviddata.github.io/covid-api/v1/places/cases.csv")
# having trouble loading from the webpage. Currently need to download to the local directory
nyt.cases <- read_csv("./us-counties.csv")
mt.cases <- nyt.cases %>% filter(state == "Montana") %>% 
  mutate(county = as.factor(county))
```

Summary of the NYtimes county level data for Montana looks like: 
```{r mt1}
summary(mt.cases)
```

The current # of cases by county are: 
```{r current}
dat.cur <- mt.cases %>% filter(date == max(date)) %>% select(county, cases, deaths)

ggplot(dat.cur, aes(x = fct_reorder(county, cases, .desc = T), y = cases)) + 
  geom_bar(stat = "identity") + labs(x = "", y = "Current cases") +
  theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1)) 

```

Plot of the cases by county in Montana, but skip the zeros for now.
```{r co-plot}
dat <- mt.cases %>% filter(cases > 0)

p <- ggplot(dat, aes(x = date, y = cases, color = county)) + 
  geom_line() +
  labs(x = "Date", y = "Cases") + theme_bw() + theme(legend.position="none") 


ggplotly(p, dynamicTicks = T)
```

And on a log scale:  
```{r co-plot-log}
# for predicted growth rates
first.day <- min(dat$date)
last.day <- max(dat$date) + 3
n.days = as.numeric(last.day - first.day + 1)

dat2 <- data.frame(date = seq(from = first.day, to = last.day, by = 1),
                   c.2 = 1.41421 ^ seq(1, n.days, 1),
                   c.4 = 1.18921 ^ seq(1, n.days, 1),
                   c.6 = 1.12246 ^ seq(1, n.days, 1)) %>% melt(id = "date")
names(dat2) <- c("date", "Td", "cases")
dat2$Td <- as.numeric(dat2$Td)*2

#plot
p.log <- ggplot(dat, aes(x = date, y = cases, color = county)) + 
  geom_line() +
 # geom_line(dat2, mapping = aes(x = date, y = cases, color = as.factor(Td)), 
 #            linetype = "dotted") + 
  scale_y_continuous(trans = 'log10') + 
  labs(x = "Date", y = "Log cases") + theme_bw() + theme(legend.position="none")  

ggplotly(p.log, dynamicTicks = T)

```
